<?xml version="1.0" encoding="utf-8"?><Database Name="FizzBuzz" Class="FizzBuzzDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PARSLEY.arvixe.com;Initial Catalog=FizzBuzz;Integrated Security=False;User ID=JosephGarza" SettingsObjectName="Common.Properties.Settings" SettingsPropertyName="FizzBuzzConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FizzBuzzs" Member="FizzBuzzDatabaseTables">
    <Type Name="FizzBuzzDatabaseTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateTimeEntered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SetUps" Member="SetUpDatabaseTables">
    <Type Name="SetUpDatabaseTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Divisor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateTimeEntered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>